stages:
  - lint
  - test

image: python:3.12

before_script:
  - python -V
  - pip install --upgrade pip
  - pip install -r requirements.txt

lint:
  stage: lint
  script:
    - make lint

test:
  stage: test
  script:
    - pytest
