"""create prices table

Revision ID: b2ef2bb3d710
Revises:
Create Date: 2026-03-18 18:24:11.143176

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2ef2bb3d710"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("prices", "ticker", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("prices", "price", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
    op.alter_column("prices", "timestamp", existing_type=sa.BIGINT(), nullable=False)
    op.drop_index(op.f("ix_prices_id"), table_name="prices")
    op.create_index("idx_ticker_timestamp", "prices", ["ticker", "timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ticker_timestamp", table_name="prices")
    op.create_index(op.f("ix_prices_id"), "prices", ["id"], unique=False)
    op.alter_column("prices", "timestamp", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("prices", "price", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
    op.alter_column("prices", "ticker", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
